# This is a sample deployment manifest file for a simple web application.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python-app
  labels:
    app: hello-python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-python-app
  template:
    metadata:
      labels:
        app: hello-python-app
    spec:
      containers:
      - name: hello-python-app
        image: mohammadirfan676/flaskt3:latest
        ports:
        - containerPort: 8080