# Service for the application
apiVersion: v1
kind: Service
metadata:
  name: hello-python-app
  labels:
    app: hello-python-app
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: hello-python-app
  type: ClusterIP